### ISSUE TITLE
Resolver errores pequeños

### ISSUE THREAD

**Issue by sergioadll** [kirodriguezke/4ga-Landing-Page#1]
Qué tal Enrique?

La página está perfecta! Sin embargo no se puede abrir cuando se entra en gitpod, Hay básicamente dos errores que lo impiden.

El primero trata sobre agregar  rel="noopener noreferrer" a los anchor en el jumbotron y en cards. Esto es por seguridad y para prevenir eventos como el phishing. Link para más finformación: https://mathiasbynens.github.io/rel-noopener/

![imagen](https://user-images.githubusercontent.com/66312531/101949256-99e5d480-3bf3-11eb-9c42-68cea905c91d.png)

El segundo ocurre porque tienes un apóstrofe ( ' ) dentro de un elemento html y te da el siguiente error:

![imagen](https://user-images.githubusercontent.com/66312531/101949804-74a59600-3bf4-11eb-87e6-02130d16e6d4.png)
 se soluciona simplemente quitando el apóstrofe.

**Comment by kirodriguezke** [comment]
Muchas gracias Sergio por tu excelente corrección, ya había puesto el atributo el="noopener noreferrer" en el navbar pero no sabia que había que ponerla cada vez que utilice el target="_blank". Ya los corregí los dos errores y lo he vuelto a subir el assignment.
